services:
  wikidump4x-neo4j:
    container_name: wikidump4x-neo4j
    privileged: true
    image: neo4j:4.4.37-enterprise
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_allow__upgrade=true
    volumes:
      - /db/neo4j/wiki4/data:/data
      - /db/neo4j/wiki4/conf:/conf
      - /db/neo4j/wiki4/logs:/logs
      - /db/neo4j/wiki4/plugins:/plugins
      - /db/neo4j/wiki4/import:/var/lib/neo4j/import

  wikidump5x-neo4j:
    container_name: wikidump5x-neo4j
    privileged: true
    image: neo4j:5.24.1-enterprise
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_server_jvm_additional=--add-modules jdk.incubator.vector
    volumes:
      - /db/neo4j/wiki5/data:/data
      - /db/neo4j/wiki5/conf:/conf
      - /db/neo4j/wiki5/logs:/logs
      - /db/neo4j/wiki5/plugins:/plugins
      - /db/neo4j/wiki5/import:/var/lib/neo4j/import
    deploy:
      resources:
        limits:
          memory: 16g
          cpus: '4'