services:
  wikidump4x-neo4j:
    container_name: wikidump4x-neo4j
    privileged: true
    image: neo4j:4.4.37-enterprise
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_allow__upgrade=true
    volumes:
      - /db/neo4j/wikidump4x/data:/data
      - /db/neo4j/wikidump4x/conf:/conf
      - /db/neo4j/wikidump4x/logs:/logs
      - /db/neo4j/wikidump4x/plugins:/plugins
      - /db/neo4j/wikidump4x/import:/var/lib/neo4j/import

  wikidump5x-neo4j:
    container_name: wikidump5x-neo4j
    privileged: true
    image: neo4j:5.24.1-enterprise
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_server_jvm_additional=--add-modules jdk.incubator.vector
    volumes:
      - /db/neo4j/wikidump5x/data:/data
      - /db/neo4j/wikidump5x/conf:/conf
      - /db/neo4j/wikidump5x/logs:/logs
      - /db/neo4j/wikidump5x/plugins:/plugins
      - /db/neo4j/wikidump5x/import:/var/lib/neo4j/import
    deploy:
      resources:
        limits:
          memory: 16g
          cpus: '4'

  wikidump5x-aerospike:
    container_name: wikidump5x-aerospike
    image: aerospike/aerospike-server:7.1.0.6_1
    ports:
      - 3001:3000
    environment:
      - DEFAULT_TTL=0 # Default time-to-live for records
      - MEM_GB=16
      - NAMESPACE=wiki
      - STORAGE_GB=128
    volumes:
      - /db/aerospike/wikidump5x:/opt/aerospike/data
    deploy:
      resources:
        limits:
          memory: 18G
        reservations:
          memory: 16G
    
  wikidump5x-mysql:
    container_name: wikidump5x-mysql
    image: mysql:9.0.1
    environment:
      MYSQL_DATABASE: wikidump5x
      MYSQL_PASSWORD: userWiki
      MYSQL_ROOT_PASSWORD: rootWiki
      MYSQL_USER: wikiuser
    ports:
      - 3307:3306
    volumes:
      - /db/mysql/wikidump5x:/var/lib/mysql